const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      slug: 'Nike-Slim-Shirt',
      Category: 'Shirt',
      image: '/images/p1.jpg',
      price: '#120',
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality shirt',
    },
    {
      _id: '2',
      name: 'Adidas Slim Shirt',
      slug: 'Adidas-Slimed-Shirt',
      Category: 'Shirt',
      image: '/images/p2.jpg',
      price: '#150',
      countInStock: 15,
      brand: 'Adidas',
      rating: 3.5,
      numReviews: 10,
      description: 'High quality shirt',
    },
    {
      _id: '3',
      name: 'Puma Slim Shirt',
      slug: 'Puma-Slim-Shirt',
      Category: 'Shirt',
      image: '/images/p3.jpg',
      price: '#170',
      countInStock: 8,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality shirt',
    },
    {
      _id: '4',
      name: 'gucci Slim Shirt',
      slug: 'gucci-Slim-Shirt',
      Category: 'Shirt',
      image: '/images/p4.png',
      price: '#100',
      countInStock: 11,
      brand: 'Gucci',
      rating: 5,
      numReviews: 10,
      description: 'High quality shirt',
    },
    {
      _id: '5',
      name: 'Uche Slim Shirt',
      slug: 'Uche-Slim-Shirt',
      Category: 'Shirt',
      image: '/images/p5.jpg',
      price: '#180',
      countInStock: 20,
      brand: 'Uche',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality shirt',
    },
  ],
};

export default data;
